### ISSUE TITLE
official pySHACL Docker image?

### ISSUE THREAD

**Issue by KonradHoeffner** [RDFLib/pySHACL#135]
Is there an official pySHACL image and if not, could you release one and upload it for example at DockerHub? I could release one myself if you prefer but I think there are some advantages if the image is created and released by the developers of the project.

**Comment by ashleysommer** [comment]
Hi @KonradHoeffner 
No, there is not, but I can easily create one. I'll publish it on Dockerhub and let you know when it's ready.

**Comment by edmondchuc** [comment]
Thoughts on using GitHub's Container registry? If it's viable, I'm happy to help set up the GitHub Actions workflow.

**Comment by KonradHoeffner** [comment]
Feel free to copy and modify the setup of https://github.com/konradhoeffner/shacl, there is a Dockerfile, entrypoint.sh and a workflow to deploy it on the GitHub container registry.
However it cannot be used exactly as it is because it takes different sets of commands, that repository is meant to integrate pySHACL into a GitHub action so that a GitHub repository containing RDF graphs can be automatically validated on push.

 ## Dockerfile
```
FROM python:3-slim
RUN pip install pyshacl==0.19.0

WORKDIR /usr/src/app
COPY entrypoint.sh .

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
```
## .github/workflows/publish-docker-yml

```
name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches: ['master']
  pull_request_target:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

The publish-docker.yml is copied from the GitHub documentation. However I'm not an expert in Docker and GitHub actions so I'm not sure if something could be improved.
